[build]
base = "python"

[phases.setup]
cmds = [
    "cd Backend && pip install fastapi uvicorn bcrypt python-jose passlib sqlalchemy ollama"
]

[phases.build]
cmds = [
    "echo 'Build completed'"
]

[start]
cmd = "cd Backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"